---
- name: Backup configuration
  hosts: all
  gather_facts: false
  tasks:
  - name: IOS BACKUP
    cisco.ios.ios_config:
      backup: true
      backup_options:
        dir_path: /home/automation/network_automation/networkautomation/backup
        filename: "{{ inventory_hostname }}-running.txt"
    when: "ansible_network_os == 'cisco.ios.ios'"

  - name: EOS BACKUP
    arista.eos.eos_config:
      backup: true
      backup_options:
        dir_path: '/home/automation/network_automation/networkautomation/backup'
        filename: "{{ inventory_hostname }}-running.txt"
    when: "ansible_network_os == 'arista.eos.eos'"


