---
- name: Gather facts
  hosts: junos
  gather_facts: false
  tasks:
  - name: Configure netconf
    vars:
      ansible_connection: ansible.netcommon.network_cli
    junipernetworks.junos.junos_netconf:
      netconf_port: 830
      state: present

  - name: Set system banner
    junipernetworks.junos.junos_banner:
      banner: login
      text: | 
        THIS IS A NEW BANNER
      state: present

  - name: Gather facts
    junipernetworks.junos.junos_facts:
      gather_subset: interfaces
        #gather_network_resources: all

    register: facts

  - name: Display facts
    debug:
      var: facts

  
